name: Tests Automatizados

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'tst/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Ejecutar Tests
      run: |
        python -m unittest discover tst
